server:
  port: 8080
  host: localhost
datasource:
  driverClassName: org.postgresql.Driver
  username: postgres
  password: root
  jdbcUrl: jdbc:postgresql://localhost:5432/postgres
  platform: postgres


